#!/bin/bash

export CROSS_DEVICE="open-pandora"
export CROSS_DEVICE_VENDOR="arm-openpandora-linux-gnueabi"
export CROSS_DEVICE_CFLAGS="-O3 -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize -fsingle-precision-constant -fsigned-char"

export CROSS_TOOLCHAINS_PATH="/opt/cross/x-tools"
export CROSS_DEVICE_TOOLCHAIN_PATH="${CROSS_TOOLCHAINS_PATH}/${CROSS_DEVICE}/${CROSS_DEVICE_VENDOR}"
export CROSS_DEVICE_TOOLCHAIN_BIN_PATH="${CROSS_DEVICE_TOOLCHAIN_PATH}/bin"
export CROSS_DEVICE_TOOLCHAIN_BIN_PREFIX_PATH="${CROSS_DEVICE_TOOLCHAIN_PATH}/bin/${CROSS_DEVICE_VENDOR}-"
export CROSS_DEVICE_TOOLCHAIN_SYSROOT_PATH="${CROSS_DEVICE_TOOLCHAIN_PATH}/${CROSS_DEVICE_VENDOR}/sysroot"

export CROSS_DEVICE_SDK_PATH="${CROSS_TOOLCHAINS_PATH}/${CROSS_DEVICE}/SDK"
export CROSS_DEVICE_OPTWARES_PATH="${CROSS_DEVICE_SDK_PATH}/opt/local"

export CROSS_MAKE_JOBS="6"
export PKG_CONFIG_PATH="${CROSS_DEVICE_SDK_PATH}/usr/lib/pkgconfig:${CROSS_DEVICE_OPTWARES_PATH}/lib/pkgconfig"
export PATH="${CROSS_DEVICE_TOOLCHAIN_BIN_PATH}:${PATH}"

if [ "${1}" != "no-export" ]; then
    export CFLAGS="-I${CROSS_DEVICE_SDK_PATH}/usr/include -I${CROSS_DEVICE_OPTWARES_PATH}/include ${CROSS_DEVICE_CFLAGS}"
    export LDFLAGS="-L${CROSS_DEVICE_TOOLCHAIN_SYSROOT_PATH}/lib -L${CROSS_DEVICE_TOOLCHAIN_SYSROOT_PATH}/usr/lib -L${CROSS_DEVICE_SDK_PATH}/lib -L${CROSS_DEVICE_SDK_PATH}/usr/lib -L${CROSS_DEVICE_OPTWARES_PATH}/lib -Wl,-rpath,${CROSS_DEVICE_SDK_PATH}/usr/lib"
fi
