#!/bin/bash

CROSS_DEVICE="open-pandora"
CROSS_DEVICE_VENDOR="arm-openpandora-linux-gnueabi"
CROSS_DEVICE_CFLAGS="-O3 -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize -fsingle-precision-constant -fsigned-char"

CROSS_TOOLCHAINS_PATH="/opt/cross/x-tools"
CROSS_DEVICE_TOOLCHAIN_PATH="${CROSS_TOOLCHAINS_PATH}/${CROSS_DEVICE}/${CROSS_DEVICE_VENDOR}"
CROSS_DEVICE_TOOLCHAIN_BIN_PATH="${CROSS_DEVICE_TOOLCHAIN_PATH}/bin"
CROSS_DEVICE_TOOLCHAIN_BIN_PREFIX_PATH="${CROSS_DEVICE_TOOLCHAIN_PATH}/bin/${CROSS_DEVICE_VENDOR}-"
CROSS_DEVICE_TOOLCHAIN_SYSROOT_PATH="${CROSS_DEVICE_TOOLCHAIN_PATH}/${CROSS_DEVICE_VENDOR}/sysroot"

CROSS_DEVICE_SDK_PATH="${CROSS_TOOLCHAINS_PATH}/${CROSS_DEVICE}/SDK"
CROSS_DEVICE_OPTWARES_PATH="${CROSS_DEVICE_SDK_PATH}/opt/local"

export PATH="${CROSS_DEVICE_TOOLCHAIN_BIN_PATH}:${PATH}"
export CFLAGS="-I${CROSS_DEVICE_SDK_PATH}/usr/include ${CROSS_DEVICE_CFLAGS}"
export LDFLAGS="-L${CROSS_DEVICE_TOOLCHAIN_SYSROOT_PATH}/lib -L${CROSS_DEVICE_TOOLCHAIN_SYSROOT_PATH}/usr/lib -L${CROSS_DEVICE_SDK_PATH}/lib -L${CROSS_DEVICE_SDK_PATH}/usr/lib -Wl,-rpath,${CROSS_DEVICE_SDK_PATH}/usr/lib"
